services:
  database:
    image: postgres:15
    pull_policy: always
    restart: always
    container_name: database
    ports:
      - '${DOCKER_HOST_IP:-127.0.0.1}:${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  graphql-server:
    image: ghcr.io/successible/cleanslate/graphql-server:latest
    pull_policy: always
    restart: always
    container_name: graphql-server
    ports:
      - '${DOCKER_HOST_IP:-127.0.0.1}:${HASURA_PORT:-8080}:8080'
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_CORS_DOMAIN: https://${DOMAIN}
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@database:5432/postgres
      HASURA_GRAPHQL_DEV_MODE: false
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
    depends_on:
      database:
        condition: service_healthy

  authentication-server:
    image: ghcr.io/successible/cleanslate/authentication-server:latest
    pull_policy: ${PULL_POLICY:-always}
    restart: always
    container_name: authentication-server
    ports:
      - '${DOCKER_HOST_IP:-127.0.0.1}:${AUTHENTICATION_SERVER_PORT:-3001}:3001'
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      JWT_SIGNING_SECRET: ${JWT_SIGNING_SECRET}
      NEXT_PUBLIC_USE_FIREBASE: ${NEXT_PUBLIC_USE_FIREBASE:-false}
    depends_on:
      - database
      - graphql-server

  client:
    image: ghcr.io/successible/cleanslate/client:latest
    pull_policy: ${PULL_POLICY:-always}
    restart: always
    container_name: client
    ports:
      - '${DOCKER_HOST_IP:-127.0.0.1}:${CLIENT_PORT:-3000}:3000'
    depends_on:
      - database
      - graphql-server

volumes:
  database:
