blank_issues_enabled: true
contact_links:
  - name: Feature request ğŸš€
    url: https://github.com/successible/cleanslate/issues/new
    about: Request a new feature
  - name: Bug ğŸª²
    url: https://github.com/successible/cleanslate/issues/new
    about: Report a bug
  - name: Chat with us ğŸ’¬
    url: https://github.com/successible/cleanslate/discussions
    about: Ask a question or give feedback
